/**
 * @tx-wat/watcher-registry
 *
 * TypeScript bindings for the WatcherRegistry Soroban smart contract.
 *
 * This file is the hand-maintained entry point. The bulk of the type-safe
 * client code is generated by `stellar contract bindings typescript` and
 * placed alongside this file during the CI publish workflow.
 *
 * If you are running locally after generating bindings, the generated
 * `Client` class and all XDR types will be available from the sibling
 * generated file. This entry point re-exports them and adds the network
 * address map so consumers can do:
 *
 *   import { Client, networks } from "@tx-wat/watcher-registry";
 *
 * @see https://github.com/Tx-wat/stellar-txwatch-contracts
 */

// ── Re-export everything from the generated bindings ─────────────────────────
// The `stellar contract bindings typescript` command writes its output to
// this directory. The generated file is typically named after the contract
// (e.g. `watcher_registry.ts`) and exports `Client`, error types, and all
// XDR-mapped TypeScript types. We re-export them wholesale so consumers
// only need to import from this package.
export * from "./watcher_registry.js";

// ── Network address map ───────────────────────────────────────────────────────
// Keyed by Stellar network name. Update contract IDs after each deployment
// by editing DEPLOYMENTS.md and running the deploy workflow — the CI
// publish-bindings job overlays the correct contract ID at publish time.

export interface NetworkConfig {
  /** Deployed contract ID (56-character Stellar address starting with C). */
  contractId: string;
  /** Stellar network passphrase. */
  networkPassphrase: string;
  /** Soroban RPC endpoint. */
  rpcUrl: string;
}

export const networks: Record<string, NetworkConfig> = {
  testnet: {
    contractId: "CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    networkPassphrase: "Test SDF Network ; September 2015",
    rpcUrl: "https://soroban-testnet.stellar.org",
  },
  mainnet: {
    contractId: "CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    networkPassphrase: "Public Global Stellar Network ; September 2015",
    rpcUrl: "https://mainnet.stellar.validationcloud.io/v1/",
  },
} as const;
